In [ ]:
!python3 -m pip install AIUT_RoboticsToolbox

In [ ]:
from AIUT_RoboticsToolbox.Toolbox import *
import numpy as np
import math

# <div dir="rtl">پیاده‌سازی تابع‌های لازم برای حل رباتیک مستقیم</div>

<div dir="rtl">
<div>

In [ ]:
def T(row):
  T = np.array([[math.cos(row[3]),                 -math.sin(row[3]),                   0,                 row[1]],
                [math.sin(row[3])*math.cos(row[0]), math.cos(row[3])*math.cos(row[0]), -math.sin(row[0]), -row[2]*math.sin(row[0])],
                [math.sin(row[3])*math.sin(row[0]), math.cos(row[3])*math.sin(row[0]),  math.cos(row[0]),  row[2]*math.cos(row[0])],
                [0,                                 0,                                  0,                 1]])
  return T

In [ ]:
def farkoo_fkin(links,joints):
  for i in range(np.size(joints)):
      if links[i][4] == 0:
          links[i][3] = joints[i]
      elif links[i][4] == 1:
          links[i][2] = joints[i]
  
  TT = np.eye(4)
  for l in range(np.size(links,0)):
    temp = T(links[l])
    TT = TT.dot(temp)

  return TT

# <div dir="rtl">بررسی صحت توابع پیاده‌سازی شده با نتایج مثال 3.3</div>

<div dir="rtl">
<div>

In [ ]:
links33 = np.array([[0.0,0.0,0.0,0.0,0],
                  [0.0,5.0,0.0,0.0,0],
                  [0.0,6.0,0.0,0.0,0]])

joints33 = [0,np.pi/2, 0]

In [ ]:
farkoo_fkin(links33, joints33)

array([[ 6.123234e-17, -1.000000e+00,  0.000000e+00,  5.000000e+00],
       [ 1.000000e+00,  6.123234e-17,  0.000000e+00,  6.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])


<div dir="rtl">

نتیجه می‌گیریم که نتایج ما با نتایج پکیج همخوانی دارد.

<div>

# Question2

# <div dir="rtl"></div>

<div dir="rtl">

سینماتیک ربات مثال 3.4 در زیر معرفی شده است و برخی از مقادیر به اختیار مقداردهی شده است.

<div>

In [ ]:
links34 = np.array([[0.0,     0.0,     0.0,     0.0, 0],
                    [np.pi/2, 0.0,     2,       0.0, 1],
                    [0.0,     0.0,     3,       0,   0]])

joints34 = [0, 0, 0]

# <div dir="rtl"></div>

<div dir="rtl">

مقادیر سینماتیک مستقیم را توسط توابعی که توسط خودم پیاده‌سازی شده است بدست می‌آورم:

<div>

In [ ]:
farkoo_fkin(links34, joints34)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  6.1232340e-17, -1.0000000e+00, -3.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  6.1232340e-17,  1.8369702e-16],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

# <div dir="rtl"></div>

<div dir="rtl">

مقادیر سینماتیک مستقیم را توسط توابعی که توسط پکیج پیاده‌سازی شده است بدست می‌آورم:

<div>

In [ ]:
robot34 = SerialLink('ex 3.4', links34)
robot34.fkin(joints34)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  6.1232340e-17, -1.0000000e+00, -3.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  6.1232340e-17,  1.8369702e-16],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

# <div dir="rtl"></div>

<div dir="rtl">

با مقایسه نتایج هر دو روش میبینیم نتایج یکسانی بدست آمده‌است.

<div>

# Question 3

# <div dir="rtl"></div>

<div dir="rtl">

سینماتیک ربات شکل 3.39 در زیر معرفی شده است و برخی از مقادیر به اختیار مقداردهی شده است.

<div>

In [ ]:
links339 = np.array([[0.0,          0.0,     0.0,     0.0,      0],
                     [0.0,          2.0,     3.0,     0.0,      1],
                     [np.pi/2,      0.0,     4.0,     0.0,      0]])

joints339 = [0, 0, 0]

# <div dir="rtl"></div>

<div dir="rtl">

مقادیر سینماتیک مستقیم را توسط توابعی که توسط خودم پیاده‌سازی شده است بدست می‌آورم:

<div>

In [ ]:
farkoo_fkin(links339, joints339)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  2.0000000e+00],
       [ 0.0000000e+00,  6.1232340e-17, -1.0000000e+00, -4.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  6.1232340e-17,  2.4492936e-16],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

# <div dir="rtl"></div>

<div dir="rtl">

مقادیر سینماتیک مستقیم را توسط توابعی که توسط پکیج پیاده‌سازی شده است بدست می‌آورم:

<div>

In [ ]:
robot34 = SerialLink('Q 3.39', links339)
robot34.fkin(joints339)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  2.0000000e+00],
       [ 0.0000000e+00,  6.1232340e-17, -1.0000000e+00, -4.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  6.1232340e-17,  2.4492936e-16],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

# <div dir="rtl"></div>

<div dir="rtl">

با مقایسه نتایج هر دو روش می‌بینیم نتایج یکسانی بدست آمده‌است.

<div>